Repository Sketcher-s/MindCandy_BE, pull requests merged in 2024-09, with the labels that each got.

#43 ✨ FEAT: 요구사항 반영 기능 추가 및 수정
  src/main/java/shop/catchmind/member/application/MemberService.java
  src/main/java/shop/catchmind/member/dto/GetPictureListResponse.java
  src/main/java/shop/catchmind/member/presentation/MemberController.java
  src/main/java/shop/catchmind/picture/application/PictureService.java
  src/main/java/shop/catchmind/picture/constant/FlaskConstant.java
  src/main/java/shop/catchmind/picture/constant/PictureErrorConstant.java
  src/main/java/shop/catchmind/picture/constant/ResultErrorConstant.java
  src/main/java/shop/catchmind/picture/domain/Picture.java
  src/main/java/shop/catchmind/picture/domain/Result.java
  src/main/java/shop/catchmind/picture/dto/PictureDto.java
  src/main/java/shop/catchmind/picture/dto/PictureRequestDto.java
  src/main/java/shop/catchmind/picture/dto/ResultDto.java
  src/main/java/shop/catchmind/picture/dto/request/RecognizeRequest.java
  src/main/java/shop/catchmind/picture/dto/request/UpdateTitleRequest.java
  src/main/java/shop/catchmind/picture/dto/response/GetPictureResponse.java
  src/main/java/shop/catchmind/picture/dto/response/InterpretResponse.java
  src/main/java/shop/catchmind/picture/dto/response/RecognitionResultResponse.java
  src/main/java/shop/catchmind/picture/dto/response/SimplePictureDto.java
  src/main/java/shop/catchmind/picture/dto/response/SimpleResultDto.java
  src/main/java/shop/catchmind/picture/exception/ResultNotFoundException.java
  src/main/java/shop/catchmind/picture/exception/UnmatchedMemberPictureException.java
  src/main/java/shop/catchmind/picture/exception/UnmatchedMemberResultException.java
  src/main/java/shop/catchmind/picture/presentation/PictureController.java
  src/main/java/shop/catchmind/picture/repository/PictureRepository.java
  src/main/java/shop/catchmind/picture/repository/ResultRepository.java
  src/main/resources/application.yml
Labels: :sparkles: Feature, :recycle: Refactor, :green_circle: 승민

#45 🔧 CHORE: Redis OSS 세팅
  build.gradle
  src/main/java/shop/catchmind/global/config/RedisConfig.java
  src/main/java/shop/catchmind/member/domain/Member.java
  src/main/resources/application.yml
Labels: :sparkles: Feature, :green_circle: 승민, :wrench: Configuration

#46 :sparkles: FEAT: 검사 API DTO 수정
  src/main/java/shop/catchmind/picture/application/PictureService.java
  src/main/java/shop/catchmind/picture/dto/request/InspectRequest.java
  src/main/java/shop/catchmind/picture/presentation/PictureController.java
Labels: :sparkles: Feature, :green_circle: 승민

#47 :sparkles: FEAT: 로그아웃 컨트롤러 및 블랙리스트 세팅
  src/main/java/shop/catchmind/auth/application/AuthService.java
  src/main/java/shop/catchmind/auth/constant/JwtConstant.java
  src/main/java/shop/catchmind/auth/presentation/AuthController.java
  src/main/java/shop/catchmind/auth/provider/JwtProvider.java
Labels: :sparkles: Feature, :orange_circle: 계환

#49 ♻️ REFACTOR: 로그아웃 검증 로직 구현 및 일부 로직 리팩토링 + 이미지 요청 form/data 문제 해결
  src/main/java/shop/catchmind/auth/application/AuthService.java
  src/main/java/shop/catchmind/auth/filter/JwtAuthProcessingFilter.java
  src/main/java/shop/catchmind/auth/provider/JwtProvider.java
  src/main/java/shop/catchmind/auth/provider/RedisProvider.java
  src/main/java/shop/catchmind/global/config/SecurityConfig.java
  src/main/java/shop/catchmind/global/config/WebConfig.java
  src/main/java/shop/catchmind/global/converter/OctetStreamReadMsgConverter.java
  src/main/java/shop/catchmind/picture/application/PictureService.java
  src/main/java/shop/catchmind/picture/domain/PictureType.java
Labels: :recycle: Refactor, :bug: Bug, :green_circle: 승민

#50 :bug: FIX: 토큰 블랙리스트 포함 검증 과정 오류 수정
  src/main/java/shop/catchmind/auth/filter/CustomJsonAuthenticationFilter.java
  src/main/java/shop/catchmind/auth/filter/JwtAuthProcessingFilter.java
  src/main/java/shop/catchmind/auth/provider/RedisProvider.java
Labels: :bug: Bug, :green_circle: 승민

#52 ♻️ REFACTOR: GPT, 그림 도메인 코드 개선 및 TODO 구현
  src/main/java/shop/catchmind/gpt/application/GptService.java
  src/main/java/shop/catchmind/gpt/constant/GptConstant.java
  src/main/java/shop/catchmind/gpt/dto/GptMessage.java
  src/main/java/shop/catchmind/gpt/presentation/GptController.java
  src/main/java/shop/catchmind/picture/application/PictureService.java
  src/main/java/shop/catchmind/picture/domain/PictureType.java
  src/main/java/shop/catchmind/picture/dto/PictureRequestDto.java
  src/main/java/shop/catchmind/picture/presentation/PictureController.java
  src/main/resources/application.yml
Labels: :sparkles: Feature, :recycle: Refactor, :green_circle: 승민

#53 ♻️ REFACTOR: 검사 요청 Dto - 소요시간 필드 수정
  src/main/java/shop/catchmind/picture/dto/request/InspectRequest.java
  src/main/resources/application.yml
Labels: :recycle: Refactor, :green_circle: 승민

#54 :recycle: REFACTOR: 소요 시간 필드 변경
  src/main/java/shop/catchmind/picture/dto/request/InspectRequest.java
  src/main/java/shop/catchmind/picture/presentation/PictureController.java
Labels: :recycle: Refactor, :green_circle: 승민
