Repository Sketcher-s/MindCandy_BE, pull requests merged in 2024-05, with the labels that each got.

#3 ✨ FEAT: GPT 연동 및 테스트
  build.gradle
  src/main/java/shop/catchmind/global/config/RestTemplateConfig.java
  src/main/java/shop/catchmind/global/config/constant/GptConstant.java
  src/main/java/shop/catchmind/gpt/application/GptService.java
  src/main/java/shop/catchmind/gpt/dto/GptMessage.java
  src/main/java/shop/catchmind/gpt/dto/GptResponse.java
  src/main/java/shop/catchmind/gpt/dto/InterpretDto.java
  src/main/java/shop/catchmind/gpt/presentation/GptController.java
  src/main/resources/application.yml
Labels: :sparkles: Feature, :orange_circle: 계환

#6 ✨ FEAT: 엔티티 설계
  src/main/java/shop/catchmind/common/AuditingField.java
  src/main/java/shop/catchmind/common/Status.java
  src/main/java/shop/catchmind/member/application/MemberService.java
  src/main/java/shop/catchmind/member/domain/Member.java
  src/main/java/shop/catchmind/member/presentation/MemberController.java
  src/main/java/shop/catchmind/member/repository/MemberRepository.java
  src/main/java/shop/catchmind/picture/application/PictureService.java
  src/main/java/shop/catchmind/picture/domain/Picture.java
  src/main/java/shop/catchmind/picture/presentation/PictureController.java
  src/main/java/shop/catchmind/picture/repository/PictureRepository.java
Labels: :sparkles: Feature, :orange_circle: 계환

#8 :sparkles: FEAT: Swagger 세팅
  build.gradle
  src/main/java/shop/catchmind/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: :sparkles: Feature, :orange_circle: 계환, :wrench: Configuration

#9 ✨ FEAT: Spring Security, JWT 인증/인가 설정 및 로직 추가
  build.gradle
  src/main/java/shop/catchmind/auth/Role.java
  src/main/java/shop/catchmind/auth/application/AuthService.java
  src/main/java/shop/catchmind/auth/dto/AuthenticationDto.java
  src/main/java/shop/catchmind/auth/filter/CustomJsonAuthenticationFilter.java
  src/main/java/shop/catchmind/auth/filter/JwtAuthProcessingFilter.java
  src/main/java/shop/catchmind/auth/handler/LoginFailureHandler.java
  src/main/java/shop/catchmind/auth/handler/LoginSuccessHandler.java
  src/main/java/shop/catchmind/auth/provider/JwtProvider.java
  src/main/java/shop/catchmind/global/config/SecurityConfig.java
  src/main/java/shop/catchmind/global/config/constant/AuthenticationProcessingConstant.java
  src/main/java/shop/catchmind/global/config/constant/AuthorityConstant.java
  src/main/java/shop/catchmind/global/config/constant/JwtConstant.java
  src/main/java/shop/catchmind/member/repository/MemberRepository.java
Labels: :sparkles: Feature, :green_circle: 승민, :wrench: Configuration

#10 ✨ FEAT: AWS S3 Config 추가
  build.gradle
  src/main/java/shop/catchmind/global/config/AmazonConfig.java
  src/main/java/shop/catchmind/global/s3/S3Provider.java
  src/main/resources/application.yml
Labels: :sparkles: Feature, :green_circle: 승민, :wrench: Configuration

#12 ✨ FEAT: 인증/인가 로직 추가
  src/main/java/shop/catchmind/auth/Role.java
  src/main/java/shop/catchmind/auth/application/AuthService.java
  src/main/java/shop/catchmind/auth/application/LoginService.java
  src/main/java/shop/catchmind/auth/constant/AuthProcessingConstant.java
  src/main/java/shop/catchmind/auth/constant/AuthRoleConstant.java
  src/main/java/shop/catchmind/auth/constant/JwtConstant.java
  src/main/java/shop/catchmind/auth/dto/request/IsExistedEmailRequest.java
  src/main/java/shop/catchmind/auth/dto/request/SignUpRequest.java
  src/main/java/shop/catchmind/auth/dto/response/IsExistedEmailResponse.java
  src/main/java/shop/catchmind/auth/filter/CustomJsonAuthenticationFilter.java
  src/main/java/shop/catchmind/auth/handler/LoginSuccessHandler.java
  src/main/java/shop/catchmind/auth/presentation/AuthController.java
  src/main/java/shop/catchmind/auth/provider/JwtProvider.java
  src/main/java/shop/catchmind/global/config/SecurityConfig.java
  src/main/java/shop/catchmind/global/config/constant/AuthorityConstant.java
  src/main/java/shop/catchmind/gpt/application/GptService.java
  src/main/java/shop/catchmind/gpt/constant/GptConstant.java
  src/main/java/shop/catchmind/member/repository/MemberRepository.java
Labels: :sparkles: Feature, :recycle: Refactor, :green_circle: 승민

#14 📝 CHORE: Auth 도메인 Swagger 문서화
  src/main/java/shop/catchmind/auth/presentation/AuthController.java
  src/main/java/shop/catchmind/common/presentation/HealthCheckController.java
  src/main/java/shop/catchmind/global/config/SwaggerConfig.java
  src/main/java/shop/catchmind/gpt/presentation/GptController.java
Labels: :recycle: Refactor, :memo: Documentation, :green_circle: 승민

#17 :ambulance: FIX: 이메일 중복 검증 API 핫픽스
  src/main/java/shop/catchmind/auth/application/AuthService.java
  src/main/java/shop/catchmind/auth/dto/request/IsExistedEmailRequest.java
  src/main/java/shop/catchmind/auth/presentation/AuthController.java
Labels: :bug: Bug, :green_circle: 승민

#18 🚑 CHORE: Url로 재설정
  src/main/java/shop/catchmind/global/config/SwaggerConfig.java
Labels: :bug: Bug, :green_circle: 승민

#20 :bug: FIX: GPT 프롬프트, temperature 수정
  src/main/java/shop/catchmind/gpt/constant/GptConstant.java
Labels: :bug: Bug, :orange_circle: 계환

#21 ✨ FEAT: 그림 검사 API 개발
  src/main/java/shop/catchmind/auth/application/AuthService.java
  src/main/java/shop/catchmind/auth/constant/JwtConstant.java
  src/main/java/shop/catchmind/auth/handler/LoginSuccessHandler.java
  src/main/java/shop/catchmind/auth/provider/JwtProvider.java
  src/main/java/shop/catchmind/global/config/SwaggerConfig.java
  src/main/java/shop/catchmind/global/s3/MultipartInputStreamFileResource.java
  src/main/java/shop/catchmind/global/s3/S3Provider.java
  src/main/java/shop/catchmind/gpt/application/GptService.java
  src/main/java/shop/catchmind/gpt/dto/NaturalLanguageDto.java
  src/main/java/shop/catchmind/gpt/presentation/GptController.java
  src/main/java/shop/catchmind/picture/application/PictureService.java
  src/main/java/shop/catchmind/picture/domain/Picture.java
  src/main/java/shop/catchmind/picture/dto/PictureDto.java
  src/main/java/shop/catchmind/picture/dto/response/InterpretResponse.java
  src/main/java/shop/catchmind/picture/presentation/PictureController.java
  src/main/resources/application.yml
Labels: :sparkles: Feature, :recycle: Refactor, :green_circle: 승민

#24 ✨ FEAT: Picture 도메인 API 구현 (검사 상세 조회, 검사 제목 수정)
  src/main/java/shop/catchmind/auth/application/AuthService.java
  src/main/java/shop/catchmind/auth/presentation/AuthController.java
  src/main/java/shop/catchmind/picture/application/PictureService.java
  src/main/java/shop/catchmind/picture/domain/Picture.java
  src/main/java/shop/catchmind/picture/dto/request/UpdateTitleRequest.java
  src/main/java/shop/catchmind/picture/dto/response/PictureResponse.java
  src/main/java/shop/catchmind/picture/presentation/PictureController.java
Labels: :sparkles: Feature, :recycle: Refactor, :green_circle: 승민

#26 ♻️ REFACTOR: 예외 처리 및 코드 포맷 수정
  src/main/java/shop/catchmind/auth/application/AuthService.java
  src/main/java/shop/catchmind/auth/application/LoginService.java
  src/main/java/shop/catchmind/auth/constant/AuthErrorConstant.java
  src/main/java/shop/catchmind/auth/dto/request/SignUpRequest.java
  src/main/java/shop/catchmind/picture/application/PictureService.java
  src/main/java/shop/catchmind/picture/constant/PictureErrorConstant.java
  src/main/java/shop/catchmind/picture/dto/request/UpdateTitleRequest.java
  src/main/java/shop/catchmind/picture/dto/response/GetPictureResponse.java
  src/main/java/shop/catchmind/picture/exception/PictureNotFoundException.java
  src/main/java/shop/catchmind/picture/exception/UnmatchedMemberPictureException.java
  src/main/java/shop/catchmind/picture/presentation/PictureController.java
Labels: :recycle: Refactor, :green_circle: 승민

#27 ✨FEAT: Member API 개발
  src/main/java/shop/catchmind/auth/dto/request/SignUpRequest.java
  src/main/java/shop/catchmind/member/application/MemberService.java
  src/main/java/shop/catchmind/member/dto/GetPictureListResponse.java
  src/main/java/shop/catchmind/member/dto/MemberDto.java
  src/main/java/shop/catchmind/member/dto/SimpleMemberDto.java
  src/main/java/shop/catchmind/member/exception/InvalidUserException.java
  src/main/java/shop/catchmind/member/presentation/MemberController.java
  src/main/java/shop/catchmind/picture/dto/PictureDto.java
  src/main/java/shop/catchmind/picture/dto/response/SimplePictureDto.java
  src/main/java/shop/catchmind/picture/repository/PictureRepository.java
Labels: :sparkles: Feature, :orange_circle: 계환

#28 🚑 FIX: UpdateTitleRequest 수정
  src/main/java/shop/catchmind/picture/dto/request/UpdateTitleRequest.java
Labels: :bug: Bug, :green_circle: 승민

#30 :bug: FIX: 객체 검출이 되지 않았을 때 예외처리 추가
  src/main/java/shop/catchmind/picture/application/PictureService.java
  src/main/resources/application.yml
Labels: :bug: Bug, :orange_circle: 계환

#31 ♻️ REFACTOR: 예외 처리 및 코드 포맷 수정
  src/main/java/shop/catchmind/auth/application/LoginService.java
  src/main/java/shop/catchmind/auth/constant/AuthProcessingConstant.java
  src/main/java/shop/catchmind/auth/dto/AuthenticationDto.java
  src/main/java/shop/catchmind/auth/handler/LoginFailureHandler.java
  src/main/java/shop/catchmind/auth/handler/LoginSuccessHandler.java
  src/main/java/shop/catchmind/auth/presentation/AuthController.java
  src/main/java/shop/catchmind/auth/provider/JwtProvider.java
  src/main/java/shop/catchmind/global/config/SecurityConfig.java
  src/main/java/shop/catchmind/gpt/application/GptService.java
  src/main/java/shop/catchmind/gpt/dto/GptResponse.java
Labels: :recycle: Refactor, :green_circle: 승민, :wrench: Configuration

#33 ♻️ CHORE: Auditing 설정 추가 및 GPT 응답 추출 정규표현식 수정
  src/main/java/shop/catchmind/CatchMindApplication.java
  src/main/java/shop/catchmind/picture/application/PictureService.java
Labels: :recycle: Refactor, :green_circle: 승민, :wrench: Configuration

#34 🚑 FIX: Docker 컨테이너 타임존 수정
  .github/workflows/deploy.yml
  src/main/resources/application.yml
Labels: :construction_worker: CI/CD, :green_circle: 승민

#36 ♻️ REFACTOR: 검사 이후 제목 설정 빈칸으로 수정
  src/main/java/shop/catchmind/picture/application/PictureService.java
  src/main/resources/application.yml
Labels: :recycle: Refactor, :green_circle: 승민, :wrench: Configuration
